version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE=student-management
      MYSQL_USER=root
      MYSQL_PASSWORD=root
      MYSQL_ROOT_PASSWORD=password
    ports:
      # MySQL Port running inside container
      - '3306:3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: